<?php

namespace Feedify\BaseBundle\Entity\Management;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriesGoogleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesGoogleRepository extends EntityRepository
{
    /**
     * @param integer|null $parent
     * @param string       $languageCode
     * @return array
     */
    public function getCategoriesByParent($parent, $languageCode = '')
    {
        $queryBuilder = $this->createQueryBuilder('cat')
            ->select('cat')
            ->where('cat.parent'.$languageCode.' = :parent')
            ->setParameter('parent', $parent)
            ->getQuery()
            ->getArrayResult();

        $categoryArray = array();
        /** @var CategoriesGoogle $category */
        foreach ($queryBuilder as $category) {
            $categoryArray[$category['id']] = $category['name'.$languageCode];
        }

        return $categoryArray;
    }
}
