<?php

namespace Feedify\BaseBundle\Entity\Management;

use Doctrine\ORM\EntityRepository;

/**
 * CountryDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryDescriptionRepository extends EntityRepository
{
    /**
     * @param int    $languageId
     * @param int    $limit
     * @param int    $offset
     * @param string $search
     * @return array
     */
    public function getCountryDescription($languageId, $limit, $offset, $search)
    {
        $queryBuilder = $this->createQueryBuilder('cd')
            ->select('cd')
            ->where('cd.languageId = :languageId')
            ->setParameter('languageId', $languageId);

        if ($search) {
            $queryBuilder
                ->andWhere('(cd.id LIKE :search OR cd.name LIKE :search)')
                ->setParameter('search', '%'.$search.'%');
        }

        if ($offset) {
            $queryBuilder->setFirstResult($offset);
        }

        if ($limit) {
            $queryBuilder->setMaxResults($limit);
        }

        return $queryBuilder->getQuery()->getResult();
    }
}
