<?php

namespace Feedify\BaseBundle\Entity\Management;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * FilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterRepository extends EntityRepository
{
    /**
     * @param int $clientId
     * @return int
     */
    public function countFilterByClientId($clientId)
    {
        $queryBuilder = $this->createQueryBuilder('f')
            ->select('COUNT(f)')
            ->where('f.clientId = :clientId')
            ->setParameter('clientId', $clientId)
            ->getQuery();

        try {
            $result = $queryBuilder->getSingleScalarResult();
        } catch (NoResultException $e) {
            $result = 0;
        }

        return $result;
    }
}
