<?php

namespace Feedify\BaseBundle\Entity\Management;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * UserTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTicketRepository extends EntityRepository
{
    /**
     * @param string $search
     * @return Pagerfanta
     */
    public function getAllUserTicket($search)
    {
        $queryBuilder = $this->createQueryBuilder('t');
        if ($search = trim($search)) {
            $queryBuilder->where("t.username LIKE '%$search%'");
        }
        $queryBuilder->orderBy('t.atDate');

        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, true, false));
    }
}
