<?php

namespace Feedify\BaseBundle\Entity\Management;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * UserMailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMailsRepository extends EntityRepository
{
    /**
     * @param array|string $search
     * @return \Pagerfanta\Pagerfanta
     */
    public function getAllUserMails($search)
    {
        /**
         * @param $search
         * @return Pagerfanta
         */
        $queryBuilder = $this->createQueryBuilder('t');
        if ($search = trim($search)) {
            $queryBuilder->where("t.username LIKE '%$search%'");
//            ->setParameter('search', $search);
        }
        $queryBuilder->orderBy('t.atDate');

        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, true, false));
    }
}
