<?php

namespace Feedify\BaseBundle\Entity\Management;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepository extends EntityRepository
{
    /**
     * @param Request $request
     * @return string
     */
    public function getWidgetsList($request)
    {
        if ($src = trim($request->get('search'))) {
            $where = "(w.username LIKE '%$src%' OR w.url LIKE '%$src%' OR w.isActive LIKE '%$src%' OR w.update LIKE '%$src%')";
        }

        if ($request->get('inactive') == 1) {
            $where = isset($where) ? $where.' AND w.isActive = 0' : 'w.isActive = 0';
        }

        if (!isset($where)) {
            $where = '1 = 1';
        }

        $sort = 'w.'.$request->get('sort', 'id');
        $by = $request->get('by', 'ASC');

        $queryBuilder = $this->createQueryBuilder('w')
            ->select('w')
            ->where($where)
            ->orderBy($sort, $by)
            ->getQuery();

        return $queryBuilder->getResult();
    }
}
