<?php

namespace Feedify\BaseBundle\Entity\Customer;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryMappingRepository extends EntityRepository
{
    /**
     * @param int $market
     */
    public function deleteMapping($market)
    {
        $this->createQueryBuilder('cm')
            ->delete()
            ->where('cm.marketId = :marketId')
            ->setParameter('marketId', $market)
            ->getQuery()
            ->execute();
    }

    /**
     * @return array
     */
    public function getDistinctMarketsId()
    {
        $queryBuilder = $this->createQueryBuilder('cm')
            ->select('cm.marketId')
            ->distinct()
            ->getQuery()
            ->getResult();

        $marketArray = array();
        foreach ($queryBuilder as $marketId) {
            $marketArray[] = $marketId['marketId'];
        }

        return $marketArray;
    }
}
