<?php

namespace Feedify\BaseBundle\Entity\Customer;

use Doctrine\ORM\EntityRepository;

/**
 * LogExportMarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method findOneByMarketId
 */
class LogExportMarketRepository extends EntityRepository
{
}
