<?php

namespace Feedify\BaseBundle\Entity\Customer;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersProductsRepository extends EntityRepository
{
    /**
     * Get all orders by product and markets
     *
     * @param array $productsId
     * @param array $data
     * @return array
     */
    public function countOrdersByProductsAndMarkets($productsId, $data)
    {
        $where = '';
        $parameters['productId'] = $productsId ?: array(0);
        if (!empty($data['startDate']) && !empty($data['endDate'])) {
            $where = ' AND o.orderDate >= :startDate AND o.orderDate <= :endDate';
            $parameters['startDate'] = $data['startDate'];
            $parameters['endDate'] = $data['endDate'];
        }

        if (!empty($data['market'])) {
            $where .= ' AND o.marketId IN (:marketsId)';
            $parameters['marketsId'] = $data['market'];
        }

        $queryBuilder = $this->createQueryBuilder('op')
            ->select('op.productId, o.marketId, COUNT(o.marketId) AS countOrders, SUM(op.productPrice * op.productQuantity) AS orderPrice')
            ->leftJoin('op.order', 'o')
            ->where('op.productId IN (:productId)'.$where)
            ->setParameters($parameters)
            ->groupBy('op.productId, o.marketId')
            ->getQuery()
            ->getResult();

        $orders = array();
        foreach ($queryBuilder as $order) {
            $orders[$order['productId']]['count'] = isset($orders[$order['productId']]['count'])
                ? $orders[$order['productId']]['count'] + $order['countOrders']
                : $order['countOrders'];

            $orders[$order['productId']]['price'] = isset($orders[$order['productId']]['price'])
                ? $orders[$order['productId']]['price'] + $order['orderPrice']
                : $order['orderPrice'];

            if (isset($orders[$order['productId']][$order['marketId']]['count'])) {
                $orders[$order['productId']][$order['marketId']]['count'] += $order['countOrders'];
            } else {
                $orders[$order['productId']][$order['marketId']]['count'] = $order['countOrders'];
            }

            if (isset($orders[$order['productId']][$order['marketId']]['price'])) {
                $orders[$order['productId']][$order['marketId']]['price'] += $order['orderPrice'];
            } else {
                $orders[$order['productId']][$order['marketId']]['price'] = $order['orderPrice'];
            }
        }

        return $orders;
    }
}
