<?php

namespace Feedify\BaseBundle\Entity\Customer;

use Doctrine\ORM\EntityRepository;

/**
 * ProvidersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvidersRepository extends EntityRepository
{
    /**
     * Get added markets by customer
     *
     * @param integer(0|1) $status
     * @return array
     */
    public function getMarketsIdByStatus($status)
    {
        $providers = $this->createQueryBuilder('p')
            ->select('p.market')
            ->where('p.status = :status')
            ->setParameter('status', $status)
            ->getQuery()
            ->getArrayResult();

        $marketsId = array();
        foreach ($providers as $provider) {
            $marketsId[] = $provider['market'];
        }

        return $marketsId;
    }
}
