<?php

namespace Feedify\BaseBundle\Entity\Management\Customer;

use Doctrine\ORM\EntityRepository;

/**
 * ExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraRepository extends EntityRepository
{
}
