<?php

namespace Feedify\BaseBundle\Entity\Management\Customer;

use Doctrine\ORM\EntityRepository;
use Feedify\BaseBundle\Constant\Management\Customer;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    /**
     * @param int $customerId
     * @return array
     */
    public function deleteCustomerRoles($customerId)
    {
        $this->createQueryBuilder('r')
            ->delete()
            ->where('r.customer = :customerId')
            ->andWhere('r.role != :role')
            ->setParameter('customerId', $customerId)
            ->setParameter('role', Customer::ROLE_USER)
            ->getQuery()
            ->execute();
    }
}
