<?php

namespace Feedify\BaseBundle\Entity\Customer\Product;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getAllCategories()
    {
        return $this->createQueryBuilder('c')
            ->select('c, p')
            ->leftJoin('c.parent', 'p')
            ->orderBy('p.id', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return mixed
     */
    public function deleteCategories()
    {
        $queryBuilder = $this
            ->createQueryBuilder('c')
            ->delete()
            ->getQuery();

        return $queryBuilder->execute();
    }

    /**
     * @param array $result
     * @return array
     */
    public function getCategoryTree(&$result)
    {
        $queryBuilder = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.parent = :parent')
            ->setParameter('parent', end($result))
            ->getQuery()
            ->getResult();

        /** @var Category $category */
        foreach ($queryBuilder as $category) {
            if (!in_array($category->getId(), $result)) {
                $result[] = $category->getId();
                $this->getCategoryTree($result);
            }
        }

        return $result;
    }
}
