<?php

namespace Feedify\BaseBundle\Entity\Customer\Product;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends EntityRepository
{
    /**
     * @param int $productId
     * @return Channel
     */
    public function loadProductChannel($productId)
    {
        $queryBuilder = $this
            ->createQueryBuilder('pc')
            ->where('pc.productId = :productId')
            ->setParameter('productId', $productId)
            ->getQuery();

        try {
            $productChannel = $queryBuilder->getSingleResult();
        } catch (\Exception $e) {
            $productChannel = new Channel();
            $productChannel->setProductId($productId);
        }

        return $productChannel;
    }
}
