<?php

namespace Feedify\BaseBundle\Entity\Customer\Product;

use Doctrine\ORM\EntityRepository;

/**
 * ProductDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDescriptionRepository extends EntityRepository
{
}
