<?php

namespace Feedify\BaseBundle\Entity\Management\Market;

use Doctrine\ORM\EntityRepository;

/**
 * MarketExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketExportRepository extends EntityRepository
{
}
